# Generated by Django 4.2.5 on 2023-09-27 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CropLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.IntegerField()),
                ('point_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.imagelabel')),
            ],
        ),
    ]
