# Generated by Django 4.2.5 on 2023-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagelabel',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='imagelabel',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='imagelabel',
            name='name',
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='mask_image',
            field=models.ImageField(default=1, max_length=600, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagelabel',
            name='original_image',
            field=models.ImageField(default=1, max_length=600, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CropLabel',
        ),
    ]
