# Generated by Django 4.2.5 on 2023-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_imagelabel_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelabel',
            name='transparent_image',
            field=models.ImageField(default=1, max_length=600, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
